version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # ports:
    #   - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ${PS_STORAGE_PATH}:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.size=${PS_STORAGE_SIZE}'
      - '--storage.tsdb.path=/var/lib/prometheus'
    restart: unless-stopped
    depends_on:
      - alertmanager
      - prometheus_bot

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "127.0.0.1:9093:9093"
    volumes:
      - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: unless-stopped
    depends_on:
      - prometheus_bot

  # https://github.com/inCaller/prometheus_bot
  # docker build -t incaller/prometheus_bot:latest .
  prometheus_bot:
    image: incaller/prometheus_bot
    container_name: prometheus_bot
    # ports:
    #   - "9087:9087"
    volumes:
      - ./configs/alert_bot/config.yaml:/config.yaml
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ${GF_STORAGE_PATH}:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - prometheus
