{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(go_info{job=\"skazhi-backend\"}, instance)"
    }
   },
   { "name": "service", "query": { "query": "label_values(go_info, service)" } },
   { "name": "interval", "query": "10s,15s,30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"skazhi-backend\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Process CPU seconds",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"skazhi-backend\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Process memory RES",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"skazhi-backend\", instance=~\"$instance\", service=~\"$service\"}",
     "legendFormat": "{{service}} - resident"
    }
   ]
  },
  {
   "title": "Process memory delta",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(process_resident_memory_bytes{job=\"skazhi-backend\", instance=~\"$instance\", service=~\"$service\"}[$__interval])",
     "legendFormat": "{{service}} - resident"
    },
    {
     "expr": "delta(process_virtual_memory_bytes{job=\"skazhi-backend\", instance=~\"$instance\", service=~\"$service\"}[$__interval])",
     "legendFormat": "{{service}} - virtual"
    }
   ]
  },
  { "title": "RMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "RMQ queue messages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(rabbitmq_queue_messages{job=\"skazhi-backend\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "RMQ connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rabbitmq_connections{job=\"skazhi-backend\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RMQ queue messages published",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(rabbitmq_queue_messages_published_total{job=\"skazhi-backend\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "RMQ memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(rabbitmq_node_mem_used{job=\"skazhi-backend\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RMQ queue message delivered",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(rabbitmq_queue_messages_delivered_total{job=\"skazhi-backend\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "RMQ node disk free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(rabbitmq_node_disk_free{job=\"skazhi-backend\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RMQ queue unacknowledged",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacknowledged{job=\"skazhi-backend\", instance=~\"$instance\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "RMQ exchanges",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rabbitmq_exchanges{job=\"skazhi-backend\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RMQ queue message redelivered",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(rabbitmq_queue_messages_redelivered_total{job=\"skazhi-backend\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "RMQ consumers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rabbitmq_consumers{job=\"skazhi-backend\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RMQ exchange messages published",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "increase(rabbitmq_exchange_messages_published_in_total{job=\"skazhi-backend\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "RMQ queue consumers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{job=\"skazhi-backend\", instance=~\"$instance\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "RMQ queue memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(rabbitmq_queue_memory{job=\"skazhi-backend\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "PG Idle in transaction",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{job=\"skazhi-backend\", datname=\"dcim\", state!~\".*idle.*\", instance=~\"$instance\"}",
     "legendFormat": "{{usename}} - {{state}}"
    }
   ]
  },
  {
   "title": "PG database size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"skazhi-backend\", datname=\"dcim\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PG stat activity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{job=\"skazhi-backend\", datname=\"dcim\", state=\"idle in transaction\", instance=~\"$instance\"}",
     "legendFormat": "{{usename}} - idle"
    },
    {
     "expr": "pg_stat_activity_count{job=\"skazhi-backend\", datname=\"dcim\", state=\"idle in transaction (aborted)\", instance=~\"$instance\"}",
     "legendFormat": "{{usename}} - aborted"
    }
   ]
  },
  {
   "title": "PG locks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "pg_locks_count{job=\"skazhi-backend\", instance=~\"$instance\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "PG long running transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "pg_long_running_transactions{job=\"skazhi-backend\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PG index tup fetch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_idx_tup_fetch{job=\"skazhi-backend\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "PG tuples",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "increase(pg_stat_database_tup_fetched{job=\"skazhi-backend\", datname=\"dcim\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "fetched"
    },
    {
     "expr": "increase(pg_stat_database_tup_updated{job=\"skazhi-backend\", datname=\"dcim\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "updated"
    },
    {
     "expr": "increase(pg_stat_database_tup_inserted{job=\"skazhi-backend\", datname=\"dcim\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "inserted"
    },
    {
     "expr": "increase(pg_stat_database_tup_deleted{job=\"skazhi-backend\", datname=\"dcim\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "deleted"
    },
    {
     "expr": "increase(pg_stat_database_tup_returned{job=\"skazhi-backend\", datname=\"dcim\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "returned"
    }
   ]
  },
  { "title": "Goroutines / FDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"skazhi-backend\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"skazhi-backend\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Go memstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "go mem allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"skazhi-backend\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{service}} - bytes allocated"
    }
   ]
  },
  {
   "title": "go memory in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"skazhi-backend\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{service}} - stack"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"skazhi-backend\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{service}} - heap"
    }
   ]
  },
  {
   "title": "go memstat delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(go_memstats_alloc_bytes_total{job=\"skazhi-backend\", instance=~\"$instance\", service=~\"$service\"}[$__interval])",
     "legendFormat": "{{service}} - alloc"
    }
   ]
  },
  {
   "title": "go memstat mallocs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(go_memstats_mallocs_total{job=\"skazhi-backend\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{service}} - alloc"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"skazhi-backend\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{service}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "Process memory VIRT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"skazhi-backend\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{service}} - virtual"
    }
   ]
  },
  {
   "title": "go memstat heap idle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"skazhi-backend\", instance=~\"$instance\", service=~\"$service\"}",
     "legendFormat": "{{service}} - alloc"
    }
   ]
  }
 ]
}